### ISSUE TITLE
The xcprepare check encoding url mismatch the cache link

### ISSUE THREAD

**Issue by Serena1993** [spotify/XCRemoteCache#124]
**My integration setup**

1. Automatic integrate
2. write .rcinfo

primary_repo: https://my-private-repo.git
cache_addresses:
 - http://localhost:8080/newcache
3. docker run locally
4. build my project

And I always get the error:
error: (XXX_Example) Postbuild step failed unsuccessfulResponse(status: 413)

Could you help me find the problem？ Thanks

**Comment by polac24** [comment]
413 HTTP response means `Payload Too Large`

The example docker file instructs setting `http://localhost:8080/cache` as a `cache_address` ([docs](https://github.com/spotify/XCRemoteCache#sample-rest-cache-server-from-a-docker-image)) - it sets 1GB max file size there. Otherwise, the max upload size is 1MB.
Please switch to `/cache` or configure [nginx.conf](https://github.com/spotify/XCRemoteCache/blob/master/backend-example/nginx.conf) accordingly so it has bigger `client_max_body_size` for your `/newcache`.

**Comment by Serena1993** [comment]
A new problem, when I use the cocoapods-plugin integration method, I can't get the correct cache link detection in the consumer mode, so I can't get the actual cache that already exists.

- [x] Run docker locally
- [x] Update Podfile mode to **producer**
- [x] Pod install
```
➜   bundle exec pod install
Prepare local specs repositories
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
[XCRC] XCRemoteCache enabled
```
- [x] Build app
- [x] uploaded cache to localhost 
<img width="1054" alt="iShot2022-04-25 22 55 46" src="https://user-images.githubusercontent.com/20840339/165117309-c9f210c4-4fea-4ab8-8dfc-f643fb429e8b.png">


- [x] Update Podfile mode to **consumer**
- []  Pod install failed
```
➜   bundle exec pod install
Prepare local specs repositories
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
[XCRC] XCRemoteCache disabled - no artifacts available
```
<img width="1054" alt="iShot2022-04-25 22 55 46" src="https://user-images.githubusercontent.com/20840339/165116458-028bb339-4029-4835-a9c3-a9a09cd5c91e.png">

**Comment by polac24** [comment]
You edited you comment so now have more context. Please try
```
'check_build_configuration' => 'DevDebug',
```
it seems to be a string, not an array.

**Comment by polac24** [comment]
The original problem seems to be resolved
